sh_test(
	name = "linux",
	srcs = ["linux.sh"],
	target_compatible_with = [
		"@platforms//os:linux"
	]
)

sh_test(
	name = "windows",
	srcs = ["windows.bat"],
	target_compatible_with = [
		"@platforms//os:windows"
	]
)
